// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrgtpavleaetbwhfsmlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyZ3RwYXZsZWFldGJ3aGZzbWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTYzOTAsImV4cCI6MjA3MDEzMjM5MH0.wJl9nhcsGGSCFeyqGiJF9_knYOJKHMkb3kRbDJT6FsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});